### ISSUE TITLE
Contribute implementation to Python

### ISSUE THREAD

**Issue by thedrow** [pydanny/cached-property#2]
See http://bugs.python.org/issue21145.
All we need to add is the TTL feature that other implementations like pip and werkzeug and Django have.

This package already has some basic testing and it would be nice to start from there.

**Comment by RonnyPfannschmidt** [comment]
just my 2 cents, once this goes into the std-lib its dead :)

**Comment by thedrow** [comment]
But there aren't many code changes to makes. It works and that's it.

**Comment by veyesecurity** [comment]
What do you think about the following workaround to handle `__slots__` classes?
```
class slots_cached_property(object):
    cached_attr_prefix = 'cached_'

    def __init__(self, func):
        self.func = func

    def __get__(self, obj, cls):
        cached_attr_name = self.cached_attr_prefix + self.func.__name__

        if not hasattr(obj, cached_attr_name):
            value = self.func(obj)
            setattr(obj, cached_attr_name, value)
        return getattr(obj, cached_attr_name)


class Foo(object):
    __slots__ = 'cached_sum', 'items'

    def __init__(self, items):
        self.items = items

    @slots_cached_property
    def sum(self):
        return sum(self.items)


foo = Foo([1, 2, 3])
print foo.sum
```

**Comment by vgavro** [comment]
As stated here http://stackoverflow.com/a/19979379/450103 with Python >= 3.2 you can use `@lru_cache` http://docs.python.org/3/library/functools.html#functools.lru_cache with `@property`, so I don't see reason to put it explicitly in stdlib:
```python
import functools
class MyClass:
    @property
    @functools.lru_cache()
    def foo(self):
        print("long calculation here")
        return 21 * 2
```

**Comment by RonnyPfannschmidt** [comment]
@vgavro your example has vastly different behavior as it creates a actual global cache disengaged from instances, and goes as far as taking away the cache from one instance when another instance is calculated

so there is a massive difference in underlying behavior and constraints

**Comment by vgavro** [comment]
@RonnyPfannschmidt you're absolutely right, came back here to update comment. Seems to be long night for me.

**Comment by pydanny** [comment]
Once we see Python 3.8 come out, I'll close this issue. However, this project will continue as it will serve as both a back port and a means to continue toying with features.

**Comment by tirkarthi** [comment]
3.8.0 is out as a stable release now with cached_property. Thanks for the library.

**Comment by thedrow** [comment]
Yup.
I'm going to close this issue.
Thank you everyone!
