### ISSUE TITLE
How does this implementation differ from the functools' cached_property?

### ISSUE THREAD

**Issue by rleibrandt** [pydanny/cached-property#246]
How does this implementation differ from the functools' cached_property? When should I use which one?

**Comment by pydanny** [comment]
LOL, functools' cached_property is influenced by this one. Unless you have an edge case, use the functools version. 

We'll update the README.

**Comment by Make42** [comment]
@pydanny: Can I invalidate the cache in the functools' version the same way? See https://github.com/pydanny/cached-property/issues/247

**Comment by MT-Cash** [comment]
@Make42 Yes. try it yourself:

```
from functools import cached_property
# from cached_property import cached_property
import random

class Foo:
    @cached_property
    def bar(self):
        return random.randint(1, 100000)

f = Foo()

print(f.bar)
print(f.bar)
print(f.bar)
print(f.bar)
del f.__dict__['bar']
print(f.bar)
print(f.bar)
print(f.bar)
```
