### ISSUE TITLE
Feature Request: cached_classproperty

### ISSUE THREAD

**Issue by guettli** [pydanny/cached-property#29]
I would like to have a cached_classproperty.

What do you think?

**Comment by RonnyPfannschmidt** [comment]
i'm not a contributor, but i'm highly skeptical of cached properties on classes instead of instances, can you outline a use-case that's a good idea?

**Comment by guettli** [comment]
@RonnyPfannschmidt could you please explain why you are "highly skeptical".

Why do you think it is a bad idea?

**Comment by RonnyPfannschmidt** [comment]
Because it's like a global variable, just hidden in a class

**Comment by guettli** [comment]
Interesting point of view.

Yes, an attribute on a class is a like global variable. That's right.

My point of view: If the attribute of a class is not computed (not coming from
a property), then it is a global variable, too. Yes it is a global variable: Coming from
a property or not.

Still I think properties at class level are useful.

**Comment by RonnyPfannschmidt** [comment]
as always freedoms of one kind are paid with restrictions of different kinds

**Comment by pydanny** [comment]
I'm on the fence. I'm like, "This is a neato idea!" However, I can't determine a good use case the same way I instantly can with the instance-based nature of cached properties.  Without a use case, I'm hesitant to add this feature.

**Comment by RonnyPfannschmidt** [comment]
At a work Projekt we just startend to remove them due to repeated issues with class properties for documentation building

**Comment by guettli** [comment]
@RonnyPfannschmidt you used them, but switched because there were issues with building docs...

Yes,  I guess tools which do introspection, will call the classed based properties and this could have side effects.

What kind of problem did you have with classed based properties?

**Comment by guettli** [comment]
About the use case. Here is a question about class based properties with 25 up-votes: http://stackoverflow.com/questions/5189699/how-can-i-make-a-class-property-in-python
OK, this only show interest, but no real use case ...

Here is our use case. We use django ORM to access PostgreSQL.

We have model "Foo" which is of a particular type. The types are stored in the model "FooType". There is a default type, and this can be accessed with `FooType.default`

```
class FooType(models.Model):
   # ...
    @classproperty
    def default(cls):
        return cls.objects.get(slug=cls.SLUG_DEFAULT)


```

Of course `FooType.get_default()` would work, too. But `FooType.default` is easier according to my point of view.

**Comment by RonnyPfannschmidt** [comment]
the correct way to have default db results in django is to make a custom manager with a manager method

and then you always have `FooType.objects.default()`

**Comment by guettli** [comment]
@RonnyPfannschmidt why is using a custom manager correct, and using a class property not?

**Comment by kmitrovic** [comment]
I got some use-case right now (not sure if there is any better way to do this without class scoped array).

I have some Django ORM classes with some fields of custom made field type within. In not only one place in the code, I need a list of fields of that type within the object I have. As this list is exactly the same for all instances of that model class, why not making that array of fields a class property and filter it out from _meta.concrete_fields only once per class per execution.
Note that my custom model class may be subclassed, and that subclass may use any number of field instantiated from my custom field type, so I don't know in advance that array I'm writing about.

**Comment by polvoazul** [comment]
I can present a use case as well:

I would like a certain class to create a connection pool. Creating such a pool is expensive so I would like to do it lazely (if I just drop it in the class definition it will be executed whenever the module is imported) and once, as all instances can share the pool.
This IS a kind of global variable, but a lazy one. If I had a way to define lazy module variables I would use them, unfortunatly I dont. I've had MANY cases like this when developing web backends. If connection pools run eagerly then they slowdown/break unittests.

If I implement this, are you willing to accept the PR?

**Comment by RonnyPfannschmidt** [comment]
@guettli a custom manager is the technically correct solution for adding custom object querying to django models and it doest introduce sneakily hidden global variables

**Comment by guettli** [comment]
More than two years later ... I changed my mind.

I think a classproperty would make trouble.

These methods would get executed in a context where it is not expected.

Examples: 

* During collecting unittests
* In IDE debugger
* Django Debug View

I think accessing the attributes of a class should not execute methods.

I think a classproperty would make trouble.

**Comment by pydanny** [comment]
Sometimes keeping the scope smaller is the right way to go.
