### ISSUE TITLE
add a cached property with idempotent invalidation

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pydanny/cached-property#31]
the fast cached property has one major drawback,
cache validation is not idempotent

to enable ease of use i propose adding a idempotent variant of the cached property,
which handles idempotent deletion

example code i did only write, not execute:

```
from cached_property import
class Example(object):
  @cached_property
  def foo(self):
    pass

del Example().foo
```

should not fail if one requests a idempotent cached property

a potential option to help with the performance hit would be using a cython spec to translate the cached property to c code for speed

**Comment by ulope** [comment]
Couldn't it simply be `self.cached_thing.invalidate()`?

**Comment by RonnyPfannschmidt** [comment]
@ulope absolutely now, the cache is invalidated iwth `del self.cached_thing` - which fails for the non-data variant

**Comment by pydanny** [comment]
I'm not opposed to this, but for cross-platform support reasons I'm concerned about using cython for speed.
