### ISSUE TITLE
Isn't there a way to empty cached results on according save operations?

### ISSUE THREAD

**Issue by oesah** [pydanny/cached-property#63]
Hey, 

I am wondering, why it wouldn't be smarter to let the decorator (somehow) clear related caches whenever a related model changes. Use Case:

I have a big model with many related models and I need to filter them for a ListView Page. To display those values I would use cached_properties for data from other models like images. Since the related instances have not changed, we could use the cached_property. Now if we upload a new image, a signal could clear the cached_property used in the other model. The same goes for update or delete operations. That way the system would always be up to date, but max out the potential of caching where ever it makes sense. 

Is that clear? I am not an expert like you, but since I am currently learning about all this, I was curious.

**Comment by pydanny** [comment]
This library is framework agnostic. It doesn't care about models or views or signals. If you want the functionality that you propose, I suggest you submit your question to the Django project.

**Comment by oesah** [comment]
Cool thanks!

**Comment by oesah** [comment]
Love your books btw :) !!
