### ISSUE TITLE
cached generator?

### ISSUE THREAD

**Issue by ava-dylang** [pydanny/cached-property#90]
I tried to wrap a generator property with this and was a bit confused, got `*** TypeError: 'generator' object is not subscriptable` back, I presume this is because the cached_property doesn't have a branch to do the necessary to capture and forward a generator and spawn a new generator on subsequent requests. [[Really as long as the output is iterable, I shoudln't really care if a list is yielded from the cache or a generator.]]

Would supporting generators be soemthing in-scope? I really like to use generators for slow-to-walk things (like say a paginated http rest api, where) caching the generated list is desirable. 

I've not done my homework on this library, you have my apologies if this is documented and I just missed it in my rush. :bowing_man: 
In my rush I am probably going to wrap generator methods, flattening them to lists as a cached property variant - though to me big extra-value in this decorator is the lack-of-need to designate cached and non-cached variants of the same property. Idk Thank you for a super helpful and super fast cache layer!

**Comment by pydanny** [comment]
It's not documented and I'm interested in your problem. Do you have a code example you can share that illustrates the issue?

**Comment by ava-dylang** [comment]
I have failed to reproduce the issue described anew with either a python2 or python3. I don't recall exactly what I was trying to do that failed - whatever it was crashed so I abandoned cached property and wrote my own dumb cache middleware for that property, and then forgot where that was. Sorry! I will be mindful to always post exmaple code in my future bug reports
